format = """
$directory\
$git_branch\
$git_commit\
$character\
"""

add_newline = false

[git_branch]
format = "[$branch]($style) "
style = "purple"

[git_commit]
format = "[$hash$tag]($style) "
style = "purple"
