format = """
$directory\
$git_branch\
$character\
"""

add_newline = false

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style) "
style = "purple"
